name: Java CI width Maven
on:
  push:
    branches:
         - main
         - Part2-SendMessages
    pull_request:
      branches:
          - main
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
         -name: Check out the code
         users: actions/checkout@v3
                                 
        -name: Set up JDK 17
         uses: actions/checkout@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven

         -name:Build project and run all tests
          run: mvn test
